### PR TITLE
Update jq-version to 1.7.1 from 1.6

### PR DESCRIPTION
**Pull request by zosopentoolsmain**

### CODE REVIEW

**Comment by HarithaIBM** [comment]
The issue was with accessing pthread_t struct, on fixing this, there were more than 50% test cases failing. This was due to calloc issue and on fixing this now It is `10 tests pass out of 16 tests - 62.50% success rate `. expected failures is 4. So analysing failure of rest of the test cases

**Review by MikeFultonDev — APPROVED** [review]
I only see one file change - did you miss some check ins ?

**Comment by HarithaIBM** [comment]
> I only see one file change - did you miss some check ins ?

I haven't committed changes yet. looks like issue is with `mktime`, sharing details in uss_tools channel to get more inputs!

**Pull request closed without merging**
